[package]
name = "override_macro_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
override_macro = { path = ".." }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
trybuild = "1.0"
